### PR TITLE
Plasmaman envirosuits now spawn on all jobs

### LINKED ISSUE #68: CE plasmamen dont spawn with envirosuits
## Round ID:
All of them

## Reproduction:
1. Be a plasmaman
2. Join as CE
3. Burn Alive

### PR DESCRIPTION
**Pull request by Merlin1230**
## About The Pull Request
fixes #68 
CE, HoP, and HoS now start with envirosuits if they are plasmamen.

## Why It's Good For The Game
Burning Bob doesn't need to burn THAT much.

### CODE REVIEW

**Comment by Kapu1178** [comment]
PR upstream please

**Comment by Merlin1230** [comment]
> PR upstream please

Sure thing! I'll do it as soon as I can.

**Comment by Merlin1230** [comment]
Porting this over to bee, I've realized these are donkstation issues, and that the explorer icon is actually _mining_. The explorer suit being missing was because porting over icons got messed up when they ported exploration. I'll revert that commit, and fix that stuff in a separate PR.

**Review by Zonespace27 — APPROVED** [review]
Will merge after #72

**Pull request merged**
