### PR TITLE
Disabling Night Shift

### PR DESCRIPTION
**Pull request by kannthus**
## About The Pull Request

Night Shift has been a massive inconvenience that interupts both antagging and roleplay on the station. It has no benefit and the maps were not designed around this feature, hence certain departments having dark spots which make it impossible to see in.  The only way around this being tampering with the APC which is entirely unneccesary for a mechanic that very Very few actually enjoy.

The suggestion of it being restricted to hallways would be _alright_, but this is a lot of dev time for a feature not many would appreciate. Especially since _This_ solution is a much easier one and in my opinion: considerably better. A poll may be required before/if this gets merged.

## Why It's Good For The Game

Massive QOL change, or as stated above.

## Changelog
:cl:
disables: Night Shift Mode
/:cl:

### CODE REVIEW

**Comment by Merlin1230** [comment]
Fix your masterrrr

**Comment by kannthus** [comment]
> Fix your masterrrr

Give me strength. I did a hard reset beforehand, your guess is as good as mine.

**Comment by Zonespace27** [comment]
PR currently undergoing vote.

**Comment by Zonespace27** [comment]
Vote succeeded, 20-5

**Pull request merged**
